language: php

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

before_script:
  - mysql -u root --password="" < config/database.sql
  - composer update
  - php vendor/bin/phpunit tests
